# Scaling

In [ ]:
Feature Scaling
The process of converting absolute values to comparable values

In [ ]:
1 --> Standard Scaling
2 --> Normalization
3 --> Min Max Scaler

In [ ]:
Normalization
- We use this we do not have the outliers

nor = (x-xmean)/(xmax- xmin)
range(0 to 1)

In [ ]:
Standard Scaling / Standardization
- We use this whe we have outliers
Z = (x-xmean)/(Xstd)
+3 to +3

In [ ]:
Min Max ---> image data
mms = (x-xmin)/(xmax- xmin)
range(0 to 1)

In [1]:
# Normalization
data = [[-1 , 2],
        [-0.5 , 6],
        [0, 10],
        [1,18]]

In [2]:
data

[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [5]:
from sklearn.preprocessing import normalize

In [6]:
normalize(data)

array([[-0.4472136 ,  0.89442719],
       [-0.08304548,  0.99654576],
       [ 0.        ,  1.        ],
       [ 0.05547002,  0.99846035]])

In [7]:
(3-5)/(10-3)

-0.2857142857142857

In [8]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()

In [9]:
data

[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [10]:
st.fit_transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [11]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()

In [12]:
mms.fit_transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [13]:
data

[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [ ]:
Imbalance data
- a data is imbalanced data if below condition is not satisfied

In [ ]:
2 * Minority >= Majority

In [ ]:
yes - 400
no - 300
maybe - 450

In [ ]:
Maj - 450
min ---> 300

In [ ]:
need to balance
Over sampling
Under Sampling

In [14]:
import pandas as pd
import numpy as np

In [15]:
pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\lenovo\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (2.3.4)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\lenovo\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\lenovo\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn->imblearn)
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.5.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn, imblearn
Successfully installed imbalanced-learn-0.14.1 imblearn-0.0 sklearn-compat-0.1.5
Note: you may need to restart the kernel to use updated packages.

In [16]:
import imblearn

In [17]:
df = pd.read_csv("Case Study Data/creditcard_fraud_data.csv")

In [18]:
df

            Time         V1         V2        V3        V4  ...       V26       V27       V28  Amount  Class
0            0.0  -1.359807  -0.072781  2.536347  1.378155  ... -0.189115  0.133558 -0.021053  149.62      0
1            0.0   1.191857   0.266151  0.166480  0.448154  ...  0.125895 -0.008983  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  1.773209  0.379780  ... -0.139097 -0.055353 -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  1.792993 -0.863291  ... -0.221929  0.062723  0.061458  123.50      0
4            2.0  -1.158233   0.877737  1.548718  0.403034  ...  0.502292  0.219422  0.215153   69.99      0
...          ...        ...        ...       ...       ...  ...       ...       ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656  ...  0.250034  0.943651  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  ... -0.395255  0.068472 -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  ... -0.087371  0.004455 -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  0.702510  0.689799  ...  0.546668  0.108821  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271  ... -0.818267 -0.002415  0.013649  217.00      0

[284807 rows x 31 columns]

In [19]:
df["Class"].unique()

array([0, 1])

In [20]:
df["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [21]:
2*492

984

In [22]:
984>=284315

False

In [25]:
# independent features
x = df.iloc[:: , :-1]

In [26]:
x

            Time         V1         V2        V3        V4  ...       V25       V26       V27       V28  Amount
0            0.0  -1.359807  -0.072781  2.536347  1.378155  ...  0.128539 -0.189115  0.133558 -0.021053  149.62
1            0.0   1.191857   0.266151  0.166480  0.448154  ...  0.167170  0.125895 -0.008983  0.014724    2.69
2            1.0  -1.358354  -1.340163  1.773209  0.379780  ... -0.327642 -0.139097 -0.055353 -0.059752  378.66
3            1.0  -0.966272  -0.185226  1.792993 -0.863291  ...  0.647376 -0.221929  0.062723  0.061458  123.50
4            2.0  -1.158233   0.877737  1.548718  0.403034  ... -0.206010  0.502292  0.219422  0.215153   69.99
...          ...        ...        ...       ...       ...  ...       ...       ...       ...       ...     ...
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656  ...  1.436807  0.250034  0.943651  0.823731    0.77
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  ... -0.606624 -0.395255  0.068472 -0.053527   24.79
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  ...  0.265745 -0.087371  0.004455 -0.026561   67.88
284805  172788.0  -0.240440   0.530483  0.702510  0.689799  ... -0.569159  0.546668  0.108821  0.104533   10.00
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271  ... -0.473649 -0.818267 -0.002415  0.013649  217.00

[284807 rows x 30 columns]

In [32]:
y = df.iloc[:: , -1:]

In [33]:
y

        Class
0           0
1           0
2           0
3           0
4           0
...       ...
284802      0
284803      0
284804      0
284805      0
284806      0

[284807 rows x 1 columns]

In [34]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()

In [35]:
X_sampled , y_sampled = ros.fit_resample(x ,y)

In [36]:
X_sampled

           Time         V1         V2         V3        V4  ...       V25       V26       V27       V28  Amount
0           0.0  -1.359807  -0.072781   2.536347  1.378155  ...  0.128539 -0.189115  0.133558 -0.021053  149.62
1           0.0   1.191857   0.266151   0.166480  0.448154  ...  0.167170  0.125895 -0.008983  0.014724    2.69
2           1.0  -1.358354  -1.340163   1.773209  0.379780  ... -0.327642 -0.139097 -0.055353 -0.059752  378.66
3           1.0  -0.966272  -0.185226   1.792993 -0.863291  ...  0.647376 -0.221929  0.062723  0.061458  123.50
4           2.0  -1.158233   0.877737   1.548718  0.403034  ... -0.206010  0.502292  0.219422  0.215153   69.99
...         ...        ...        ...        ...       ...  ...       ...       ...       ...       ...     ...
568625  51112.0  -9.848776   7.365546 -12.898538  4.273323  ...  0.538665 -0.263934  1.134095  0.225973   99.99
568626  94362.0 -26.457745  16.497472 -30.177317  8.904157  ... -0.738097 -0.966564 -7.263482 -1.324884    1.00
568627  41285.0 -12.835760   6.574615 -12.788462  8.786257  ...  0.125865  0.177624 -0.817680 -0.521030   37.32
568628   7740.0   1.023874   2.001485  -4.769752  3.819195  ... -2.032068  0.366778  0.395171  0.020206    1.00
568629  77182.0  -1.410852   2.268271  -2.297554  1.871331  ...  0.118473 -0.484537  0.373596  0.187657    1.00

[568630 rows x 30 columns]

In [37]:
y_sampled

        Class
0           0
1           0
2           0
3           0
4           0
...       ...
568625      1
568626      1
568627      1
568628      1
568629      1

[568630 rows x 1 columns]

In [38]:
y_sampled.value_counts()

Class
0        284315
1        284315
Name: count, dtype: int64

https://archive.ics.uci.edu/datasets

https://www.kaggle.com/

In [ ]:
300 CR
GCC

In [ ]:
Random Forest
XG boost

In [ ]:
DE ---> Python, Hadoop , Hive , Sqoop,  Spark, SQL , Streaming , CI CD 
DA ---> SQL , Excel , Power BI/tableau , Mongodb
DS ---> Python , stats , ML , DL , NLP , Gen AI

In [ ]:
Spark