In [1]:
pwd

'C:\\Users\\Lenovo\\Desktop\\16 Feb'

In [2]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 6CE9-051B

 Directory of C:\Users\Lenovo\Desktop\16 Feb

30-03-2026  20:12    <DIR>          .
30-03-2026  20:12    <DIR>          ..
30-03-2026  20:12    <DIR>          .ipynb_checkpoints
16-03-2026  21:21    <DIR>          __pycache__
17-03-2026  22:41               109 abc.txt
03-03-2026  20:12             1,610 Class1_anaconda_installation.ipynb
03-03-2026  22:40            40,281 class10_list_comp_exercises.ipynb
05-03-2026  22:22            67,066 Class11_tuple_dict.ipynb
09-03-2026  22:33           110,932 Class12_dict_methods_set_Conditional_statements.ipynb
10-03-2026  22:42            44,586 Class13_loops.ipynb
11-03-2026  22:43         4,320,470 Class14_Functions.ipynb
17-03-2026  22:45            59,593 Class15_Functions_2.ipynb
16-03-2026  22:28           111,056 Class16_function_3_modules_FileHandling.ipynb
17-03-2026  22:42            64,164 Class17_File_Handling_2.ipynb
23-03-2026  20:22            71,867 Class18_Exception_Handling_Regex_1.ipynb
23-03-2026  22:33           539,025 Class19_Regex_2.ipynb
17-02-2026  22:40            22,550 Class2_Intro_to_Python.ipynb
18-02-2026  22:43            46,599 Class3_Python_Components.ipynb
19-02-2026  22:29           574,793 Class4_Operations_in_Python.ipynb
23-02-2026  22:39            68,907 Class5_float_complex_bool_None_str.ipynb
25-02-2026  21:46           515,873 Class6_f_str_str_properties_indexing_Slicing.ipynb
26-02-2026  20:28            52,218 Class7_str_operation_methods.ipynb
02-03-2026  20:23            63,371 Class8_Str_methods_Sequence_ch_list.ipynb
03-03-2026  20:51            83,474 Class9_list_list_methods.ipynb
26-03-2026  21:03    <DIR>          datasets
24-02-2026  20:24           291,571 image.png
25-03-2026  21:58            41,191 iron man.jpg
17-03-2026  21:06                 0 my_file.txt
16-03-2026  21:29               602 my_module.py
24-03-2026  22:44           188,099 Numpy_Class_1.ipynb
25-03-2026  22:39         2,674,918 Numpy_Class_2.ipynb
26-03-2026  22:23           127,696 Pandas_Class_1.ipynb
30-03-2026  20:11               337 Pandas_Class2.ipynb
              28 File(s)     10,182,958 bytes
               5 Dir(s)  52,139,831,296 bytes free

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [5]:
weather_data = pd.read_csv(r"datasets/weather_data.csv")

In [6]:
weather_data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
# Attributes of DF

In [ ]:
shape , size , dim

In [10]:
s = weather_data.shape
s

(6, 4)

In [8]:
weather_data.size

24

In [9]:
weather_data.ndim

2

In [11]:
type(s)

tuple

# head()
- it displays top data from the DF(default 5 rows)

In [12]:
weather_data.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

# tail()
- it displays bottom data from the DF(default 5 rows)

In [13]:
weather_data.tail()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [14]:
weather_data.head(20)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [15]:
weather_data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [19]:
weather_data.head(2)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

# columns

In [20]:
weather_data.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

# info()

In [21]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          6 non-null      object
 1   temperature  6 non-null      int64
 2   windspeed    6 non-null      int64
 3   event        6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
1 - column names
2 - dtype of col
3 - no of rows
4 - no of columns
5 - Null value
6 - Memory

In [ ]:
	"1/1/2017"

In [22]:
my_d = {"year":pd.Series([1990, 1994,1998,2002,2004]),
    "country":pd.Series(["Italy" , "USA" , "France" , "Japan"]),
    "winner":pd.Series(["Germany" , "Brazil" , "France" , "India"]),
    }
my_DF = pd.DataFrame(my_d)

In [23]:
my_DF

   year country   winner
0  1990   Italy  Germany
1  1994     USA   Brazil
2  1998  France   France
3  2002   Japan    India
4  2004     NaN      NaN

In [24]:
my_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     5 non-null      int64
 1   country  4 non-null      object
 2   winner   4 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [25]:
5- 4

1

# Statistical Summary

In [27]:
weather_data.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
numerical column----> continuous data (Regression)
yes/no/Maybe-----> Categorical data (Classification)
2

In [28]:
weather_data.describe(include="all")

             day  temperature  windspeed event
count          6     6.000000   6.000000     6
unique         6          NaN        NaN     3
top     1/1/2017          NaN        NaN  Rain
freq           1          NaN        NaN     2
mean         NaN    30.333333   4.666667   NaN
std          NaN     3.829708   2.338090   NaN
min          NaN    24.000000   2.000000   NaN
25%          NaN    28.750000   2.500000   NaN
50%          NaN    31.500000   5.000000   NaN
75%          NaN    32.000000   6.750000   NaN
max          NaN    35.000000   7.000000   NaN

In [29]:
bike = pd.read_csv("datasets/citibike_tripdata.csv")

In [30]:
bike.head(20)

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
6,577,2018-05-01 05:05:46,2018-05-01 05:15:23,3225,Baldwin at Montgomery,3186,Grove St PATH,33619,Annual Membership from Citi Bike App,Subscriber
7,830,2018-05-01 05:11:50,2018-05-01 05:25:41,3207,Oakland Ave,3185,City Hall,33624,Annual Membership,Subscriber
8,395,2018-05-01 05:12:07,2018-05-01 05:18:42,3225,Baldwin at Montgomery,3186,Grove St PATH,26300,Annual Membership,Subscriber
9,170,2018-05-01 05:13:52,2018-05-01 05:16:43,3206,Hilltop,3195,Sip Ave,33555,$25 Off Annual Membership,Subscriber
10,353,2018-05-01 05:18:36,2018-05-01 05:24:29,3225,Baldwin at Montgomery,3195,Sip Ave,33627,Annual Membership,Subscriber
11,704,2018-05-01 05:23:26,2018-05-01 05:35:11,3185,City Hall,3187,Warren St,26216,Annual Membership,Subscriber
12,265,2018-05-01 05:23:32,2018-05-01 05:27:58,3269,Brunswick & 6th,3186,Grove St PATH,33592,Annual Membership,Subscriber
13,428,2018-05-01 05:31:40,2018-05-01 05:38:48,3212,Christ Hospital,3186,Grove St PATH,26160,Annual Membership from Citi Bike App,Subscriber
14,473,2018-05-01 05:34:23,2018-05-01 05:42:16,3225,Baldwin at Montgomery,3186,Grove St PATH,33640,Annual Membership,Subscriber
15,178,2018-05-01 05:34:30,2018-05-01 05:37:28,3267,Morris Canal,3183,Exchange Place,26190,Annual Membership,Subscriber
16,309,2018-05-01 05:41:11,2018-05-01 05:46:21,3207,Oakland Ave,3195,Sip Ave,29530,Annual Membership,Subscriber
17,126,2018-05-01 05:53:34,2018-05-01 05:55:40,3214,Essex Light Rail,3184,Paulus Hook,26163,Annual Membership,Subscriber
18,184,2018-05-01 05:53:42,2018-05-01 05:56:46,3276,Marin Light Rail,3186,Grove St PATH,29571,Annual Membership,Subscriber
19,170,2018-05-01 05:53:43,2018-05-01 05:56:33,3267,Morris Canal,3184,Paulus Hook,33634,Join Citi Bike for $14.95/month,Subscriber

# indexing and Slicing of Data Frame

In [31]:
bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32428 entries, 0 to 32427
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tripduration         32428 non-null  int64
 1   starttime            32428 non-null  object
 2   stoptime             32428 non-null  object
 3   start station id     32428 non-null  int64
 4   start station name   32428 non-null  object
 5   end station id       32428 non-null  int64
 6   end station name     32428 non-null  object
 7   bikeid               32428 non-null  int64
 8   name_localizedValue  32428 non-null  object
 9   usertype             32428 non-null  object
dtypes: int64(4), object(6)
memory usage: 2.5+ MB

In [32]:
bike.describe()

        tripduration  start station id  end station id        bikeid
count   32428.000000      32428.000000    32428.000000  32428.000000
mean      798.978352       3264.568829     3255.485568  29817.647959
std      9961.203954        137.810344      149.390306   2807.705863
min        61.000000       3183.000000      212.000000  15271.000000
25%       236.000000       3192.000000     3186.000000  26310.000000
50%       352.000000       3206.000000     3203.000000  29516.000000
75%       590.000000       3272.000000     3270.000000  33568.000000
max    936970.000000       3681.000000     3681.000000  33682.000000

In [33]:
# column
bike.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'end station id', 'end station name', 'bikeid',
       'name_localizedValue', 'usertype'],
      dtype='object')

In [ ]:
# getting columns we want

In [36]:
time = bike[["starttime" , "stoptime"]]

In [37]:
time

                 starttime             stoptime
0      2018-05-01 00:04:47  2018-05-01 00:10:25
1      2018-05-01 01:31:10  2018-05-01 01:55:53
2      2018-05-01 01:31:29  2018-05-01 01:35:22
3      2018-05-01 02:03:29  2018-05-01 02:06:40
4      2018-05-01 04:27:12  2018-05-01 04:32:16
...                    ...                  ...
32423  2018-05-30 13:49:18  2018-05-30 13:55:55
32424  2018-05-30 13:49:21  2018-05-30 13:54:35
32425  2018-05-30 13:49:51  2018-05-30 13:55:08
32426  2018-05-30 13:50:52  2018-05-30 14:09:42
32427  2018-05-30 13:50:58  2018-05-30 13:57:08

[32428 rows x 2 columns]

In [38]:
bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,15271,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

In [ ]:
# at[]

In [41]:
print(bike.at[5 , "bikeid"])

29298

In [44]:
print(bike.to_string())

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [46]:
bike.at[4 , "bikeid"]

np.int64(15271)

In [47]:
bike.at[4 , "bikeid"] = 9999999

In [48]:
bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

# Slicing Methods onn DF

# 1 Normal Slicing
- both numeric and row_name slicing is possible
- Only Row wise Slicing is allowed

In [ ]:
syntax-1
            dataframe[start: stop: step]

In [ ]:
syntax-2
datafram[row_name_start:row_name_stop:step]

In [49]:
bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

# based on the index number

In [52]:
bike[1:201:]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
196,632,2018-05-01 08:08:19,2018-05-01 08:18:52,3277,Communipaw & Berry Lane,3186,Grove St PATH,33572,FREE Bonus Month with Annual Membership,Subscriber
197,563,2018-05-01 08:08:26,2018-05-01 08:17:50,3199,Newport Pkwy,3184,Paulus Hook,29293,Annual Membership,Subscriber
198,218,2018-05-01 08:08:32,2018-05-01 08:12:10,3267,Morris Canal,3183,Exchange Place,33640,$25 Off Annual Membership,Subscriber
199,224,2018-05-01 08:09:21,2018-05-01 08:13:06,3194,McGinley Square,3195,Sip Ave,33652,Annual Membership,Subscriber
200,215,2018-05-01 08:10:14,2018-05-01 08:13:49,3209,Brunswick St,3186,Grove St PATH,29127,$25 Off Annual Membership,Subscriber

In [ ]:
bike[1:200:3]

In [53]:
bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

In [54]:
new_bike = bike[0:6:]
new_bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
5,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber

In [55]:
new_bike.index

RangeIndex(start=0, stop=6, step=1)

In [56]:
["row_"] * 5

['row_', 'row_', 'row_', 'row_', 'row_']

In [59]:
idx = ['row_1', 'row_2', 'row_3', 'row_4', 'row_5' , "row_6"]

In [60]:
new_bike.index = idx

In [61]:
new_bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
row_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
row_6,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber

In [ ]:
# using index number

In [62]:
new_bike[1:4:]  # Stop is Exlusive

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer

In [ ]:
# using index we have given

In [63]:
new_bike["row_2":"row_4":] # Stop is not Exlusive

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer

In [ ]:
new_bike

In [67]:
new_bike[['tripduration' , 'bikeid']]

       tripduration   bikeid
row_1           338    33558
row_2          1482    33593
row_3           232    29217
row_4           190    29662
row_5           303  9999999
row_6           176    29298

In [69]:
new_bike[0:3 , 0:5 ]

InvalidIndexError: (slice(0, 3, None), slice(0, 5, None))

In [ ]:
# loc
- does slicing on both rows and columns
- it will do slicing only by the given index

In [ ]:
syntax
dataframe.loc[row_name_start:row_name_stop:row_step ,column_name_start : column_name:stop: column_step ]

In [70]:
new_bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
row_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
row_6,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber

In [ ]:
# index numbers

In [71]:
new_bike.loc[1:5: , 0:4:]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [73]:
new_bike.loc["row_2":"row_5": , "tripduration":"start station id": ]

,tripduration,starttime,stoptime,start station id
row_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185
row_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207

In [74]:
bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
0,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
1,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
2,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
3,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
4,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
...,...,...,...,...,...,...,...,...,...,...
32423,396,2018-05-30 13:49:18,2018-05-30 13:55:55,3184,Paulus Hook,3279,Dixon Mills,29639,Join Citi Bike for $14.95/month,Subscriber
32424,313,2018-05-30 13:49:21,2018-05-30 13:54:35,3202,Newport PATH,3639,Harborside,26301,$25 Off Annual Membership,Subscriber
32425,316,2018-05-30 13:49:51,2018-05-30 13:55:08,3220,5 Corners Library,3195,Sip Ave,29260,Annual Membership,Subscriber
32426,1130,2018-05-30 13:50:52,2018-05-30 14:09:42,3281,Leonard Gordon Park,3213,Van Vorst Park,26239,Annual Membership,Subscriber
32427,369,2018-05-30 13:50:58,2018-05-30 13:57:08,3220,5 Corners Library,3207,Oakland Ave,33660,Annual Membership,Subscriber

In [76]:
bike.loc[2:6: , "tripduration":"start station id": ]

   tripduration            starttime             stoptime  start station id
2           232  2018-05-01 01:31:29  2018-05-01 01:35:22              3194
3           190  2018-05-01 02:03:29  2018-05-01 02:06:40              3185
4           303  2018-05-01 04:27:12  2018-05-01 04:32:16              3207
5           176  2018-05-01 04:37:05  2018-05-01 04:40:01              3194
6           577  2018-05-01 05:05:46  2018-05-01 05:15:23              3225

In [77]:
new_bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
row_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
row_6,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber

In [ ]:
iloc

In [78]:
new_bike.iloc["row_2":"row_5": , "tripduration":"start station id": ]

TypeError: cannot do positional indexing on Index with these indexers [tripduration] of type str

In [79]:
new_bike.iloc[1:5: , "tripduration":"start station id": ]

TypeError: cannot do positional indexing on Index with these indexers [tripduration] of type str

In [80]:
new_bike.iloc[1:5: , 0:4: ]

,tripduration,starttime,stoptime,start station id
row_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185
row_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207

# Normal Slicing
- Only row slicing is allowed
- can slice based on index numbers or given Indexes

# loc
- row wise as well as column wise slicing is allowed
- Only the given index should be used( exception - if index numbers are available those can be used)

# iloc
- row wise as well as column wise slicing is allowed
- Only the  index numbers should be used

In [81]:
new_bike

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_1,338,2018-05-01 00:04:47,2018-05-01 00:10:25,3639,Harborside,3199,Newport Pkwy,33558,Annual Membership,Subscriber
row_2,1482,2018-05-01 01:31:10,2018-05-01 01:55:53,3681,Grand St,3185,City Hall,33593,24 Hour,Customer
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer
row_5,303,2018-05-01 04:27:12,2018-05-01 04:32:16,3207,Oakland Ave,3195,Sip Ave,9999999,Annual Membership,Subscriber
row_6,176,2018-05-01 04:37:05,2018-05-01 04:40:01,3194,McGinley Square,3195,Sip Ave,29298,Annual Membership,Subscriber

In [82]:
# loc
new_bike.loc["row_3":"row_4",]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer

In [84]:
# iloc
new_bike.iloc["row_3":"row_4",]

TypeError: cannot do positional indexing on Index with these indexers [row_3] of type str

In [85]:
# iloc
new_bike.iloc[2:4 ]

,tripduration,starttime,stoptime,start station id,start station name,end station id,end station name,bikeid,name_localizedValue,usertype
row_3,232,2018-05-01 01:31:29,2018-05-01 01:35:22,3194,McGinley Square,3193,Lincoln Park,29217,FREE Bonus Month with Annual Membership,Subscriber
row_4,190,2018-05-01 02:03:29,2018-05-01 02:06:40,3185,City Hall,3186,Grove St PATH,29662,24 Hour,Customer

In [86]:
inter_or = pd.read_csv("datasets/international_org.csv")

In [87]:
inter_or

  Organization Name  Headquater
0               FAO        Rome
1               ICJ   The Hague
2               IMF  Washington
3            UNESCO       Paris
4               UNO    New York
5        World Bank  Washington

In [ ]:
# adding a column

In [89]:
inter_or["year"]

KeyError: 'year'

In [90]:
inter_or["year"] = 2026

In [91]:
inter_or

  Organization Name  Headquater  year
0               FAO        Rome  2026
1               ICJ   The Hague  2026
2               IMF  Washington  2026
3            UNESCO       Paris  2026
4               UNO    New York  2026
5        World Bank  Washington  2026

In [92]:
lst = [2020,2021,2022,2023,2024,2025]

In [93]:
inter_or["year"] = lst

In [94]:
inter_or

  Organization Name  Headquater  year
0               FAO        Rome  2020
1               ICJ   The Hague  2021
2               IMF  Washington  2022
3            UNESCO       Paris  2023
4               UNO    New York  2024
5        World Bank  Washington  2025

In [95]:
rating = pd.read_csv("datasets/imdb_rating.csv")

In [96]:
rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [97]:
rating.replace("Crime" , "XYZ")

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,XYZ,142
1,9.2,The Godfather,XYZ,175
2,9.1,The Godfather: Part II,XYZ,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,XYZ,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [98]:
rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [99]:
rating.replace("Crime" , "XYZ" , inplace=True)

In [100]:
rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,XYZ,142
1,9.2,The Godfather,XYZ,175
2,9.1,The Godfather: Part II,XYZ,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,XYZ,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [101]:
rating = pd.read_csv("datasets/imdb_rating.csv")

In [102]:
rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [104]:
rating["genre"].replace("Crime" , "00000" , inplace=True)

In [105]:
rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,00000,142
1,9.2,The Godfather,00000,175
2,9.1,The Godfather: Part II,00000,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,00000,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [ ]:
# Dropping

In [106]:
rating.drop(columns='duration')

   star_rating                                          title      genre
0          9.3                       The Shawshank Redemption      00000
1          9.2                                  The Godfather      00000
2          9.1                         The Godfather: Part II      00000
3          9.0                                The Dark Knight     Action
4          8.9                                   Pulp Fiction      00000
5          8.9                                   12 Angry Men      Drama
6          8.9                 The Good, the Bad and the Ugly    Western
7          8.9  The Lord of the Rings: The Return of the King  Adventure
8          8.9                               Schindler's List  Biography
9          8.9                                     Fight Club      Drama

In [107]:
rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,00000,142
1,9.2,The Godfather,00000,175
2,9.1,The Godfather: Part II,00000,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,00000,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [108]:
rating.drop(columns='duration' , inplace=True)

In [109]:
rating

   star_rating                                          title      genre
0          9.3                       The Shawshank Redemption      00000
1          9.2                                  The Godfather      00000
2          9.1                         The Godfather: Part II      00000
3          9.0                                The Dark Knight     Action
4          8.9                                   Pulp Fiction      00000
5          8.9                                   12 Angry Men      Drama
6          8.9                 The Good, the Bad and the Ugly    Western
7          8.9  The Lord of the Rings: The Return of the King  Adventure
8          8.9                               Schindler's List  Biography
9          8.9                                     Fight Club      Drama

In [110]:
rating.drop(columns=["title" , "genre"] , inplace=True)

In [111]:
rating

   star_rating
0          9.3
1          9.2
2          9.1
3          9.0
4          8.9
5          8.9
6          8.9
7          8.9
8          8.9
9          8.9

In [112]:
rating = pd.read_csv("datasets/imdb_rating.csv")

In [113]:
rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [114]:
rating.drop(index=1)

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [116]:
ne_df = rating.drop(index=[1,2,3,4])

In [117]:
ne_df

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [118]:
# Sorting
rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [120]:
# Ascending order
rating.sort_values(by="star_rating" , ascending=True)

,star_rating,title,genre,duration
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139
3,9.0,The Dark Knight,Action,152
2,9.1,The Godfather: Part II,Crime,200
1,9.2,The Godfather,Crime,175
0,9.3,The Shawshank Redemption,Crime,142

In [121]:
# Descending order
rating.sort_values(by="star_rating" , ascending=False)

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139

In [123]:
# Descending order
rating.sort_values( by=4 , axis=1)

UFuncTypeError: ufunc 'greater' did not contain a loop with signature matching types (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.StrDType'>) -> None

In [124]:
# Descending order
rating.sort_values( by="star rating" , axis=1)

KeyError: 'star rating'

In [126]:
# Descending order
rating.sort_index(axis=1)

,duration,genre,star_rating,title
0,142,Crime,9.3,The Shawshank Redemption
1,175,Crime,9.2,The Godfather
2,200,Crime,9.1,The Godfather: Part II
3,152,Action,9.0,The Dark Knight
4,154,Crime,8.9,Pulp Fiction
5,96,Drama,8.9,12 Angry Men
6,161,Western,8.9,"The Good, the Bad and the Ugly"
7,201,Adventure,8.9,The Lord of the Rings: The Return of the King
8,195,Biography,8.9,Schindler's List
9,139,Drama,8.9,Fight Club

In [128]:
# Descending order
rating['star_rating'].sort_values( ascending=False)

0    9.3
1    9.2
2    9.1
3    9.0
4    8.9
5    8.9
6    8.9
7    8.9
8    8.9
9    8.9
Name: star_rating, dtype: float64

In [131]:
# Descending order
rating.sort_values(by="star_rating" , ascending=True , inplace=True)

In [132]:
rating

,star_rating,title,genre,duration
4,8.9,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139
3,9.0,The Dark Knight,Action,152
2,9.1,The Godfather: Part II,Crime,200
1,9.2,The Godfather,Crime,175
0,9.3,The Shawshank Redemption,Crime,142

KeyError: "None of ['star rating'] are in the columns"

In [133]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

In [134]:
rating.set_index(keys=)

TypeError: DataFrame.set_index() missing 1 required positional argument: 'keys'

In [137]:
rating.reset_index( )

,index,star_rating,title,genre,duration
0,4,8.9,Pulp Fiction,Crime,154
1,5,8.9,12 Angry Men,Drama,96
2,6,8.9,"The Good, the Bad and the Ugly",Western,161
3,7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
4,8,8.9,Schindler's List,Biography,195
5,9,8.9,Fight Club,Drama,139
6,3,9.0,The Dark Knight,Action,152
7,2,9.1,The Godfather: Part II,Crime,200
8,1,9.2,The Godfather,Crime,175
9,0,9.3,The Shawshank Redemption,Crime,142

In [138]:
rating.reset_index( drop=True)

,star_rating,title,genre,duration
0,8.9,Pulp Fiction,Crime,154
1,8.9,12 Angry Men,Drama,96
2,8.9,"The Good, the Bad and the Ugly",Western,161
3,8.9,The Lord of the Rings: The Return of the King,Adventure,201
4,8.9,Schindler's List,Biography,195
5,8.9,Fight Club,Drama,139
6,9.0,The Dark Knight,Action,152
7,9.1,The Godfather: Part II,Crime,200
8,9.2,The Godfather,Crime,175
9,9.3,The Shawshank Redemption,Crime,142

In [139]:
# Descending order
rating.sort_values(by="title" , ascending=True )

,star_rating,title,genre,duration
5,8.9,12 Angry Men,Drama,96
9,8.9,Fight Club,Drama,139
4,8.9,Pulp Fiction,Crime,154
8,8.9,Schindler's List,Biography,195
3,9.0,The Dark Knight,Action,152
1,9.2,The Godfather,Crime,175
2,9.1,The Godfather: Part II,Crime,200
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
0,9.3,The Shawshank Redemption,Crime,142

In [142]:
rating.at[4 , "star_rating"] = "Tapas"

In [143]:
rating

,star_rating,title,genre,duration
4,Tapas,Pulp Fiction,Crime,154
5,8.9,12 Angry Men,Drama,96
6,8.9,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.9,Schindler's List,Biography,195
9,8.9,Fight Club,Drama,139
3,9.0,The Dark Knight,Action,152
2,9.1,The Godfather: Part II,Crime,200
1,9.2,The Godfather,Crime,175
0,9.3,The Shawshank Redemption,Crime,142

In [144]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 4 to 0
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   star_rating  10 non-null     object
 1   title        10 non-null     object
 2   genre        10 non-null     object
 3   duration     10 non-null     int64
dtypes: int64(1), object(3)
memory usage: 700.0+ bytes